import Head from 'next/head'
// import Image from 'next/image'
// import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { Overpass } from '@next/font/google'
import { Button, Center, Circle, Text, HStack, Box, Image, VStack, Flex } from '@chakra-ui/react';
import { useState } from 'react';

// const inter = Inter({ subsets: ['latin'] })
const over = Overpass({ weight: ['400','700'], subsets:['latin']});
const RatingBtn = ({number, handle, back, col})=>{
  return <Circle as='button' size='40px' bg={back} color={col} 
  _hover={{bg:'brand.lightgrey', color:'brand.white'}}
  _active={{bg:'brand.orange', color:'brand.white'}}
  onClick={handle}
  >{number}</Circle>
}
const Content = ()=>{
  return <button style={{backgroundColor:'yellow'}} onClick={function() { console.log('click');}} >wdae</button>
}

export default function Home() {
  const [rating, setRating] = useState(0);
  const [latar, setLatar] = useState(Array(5).fill("brand.mediumgrey"));
  const [warna, setWarna] = useState(Array(5).fill("brand.lightgrey"));
  const [isInit, setIsInit] = useState(true);

  function clickHandle(num){
    setRating(num);
    console.log(num);
    // const initLatar = Array(5).fill("brand.mediumgrey");
    // const initWarna = Array(5).fill("brand.lightgrey");
    // setLatar(initLatar);
    // setWarna(initWarna);
    latar.forEach((val, idx)=>{
      latar[idx] = (idx == num-1)?  "brand.orange" : "brand.mediumgrey";
      warna[idx] = (idx == num-1)?  "brand.white" : "brand.lightgrey";
    })
    console.log(latar);
    // latar[num-1] = "brand.orange";
    // warna[num-1] ='brand.white';
  }
  function clickSubmit(){
    setIsInit(false)
  }
  return (
    <>
      <Head>
        <title>Interactive Rating Component Main</title>
        <meta name="description" content="Generated by Nida Nido" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/favicon-32x32.png" />
      </Head>
      <main className={over.className} fontSize='15px'>
        <Center bg='brand.dark' w='100vw' h='100vh'>
          {isInit?
            <Flex flexDir='column' justifyContent='space-between'
                    w={['90vw', '50vh']} h={['90vw', '50vh']} bg='brand.darkblue' 
                    p='20px' borderRadius='10px'
                    spacing='15px'
                    >
              <Circle bg='brand.mediumgrey' size='30px'>
              <Image src='/images/icon-star.svg' width='15px' height='15px' />
              </Circle>
              
              <Text color='brand.white' fontSize='25px' lineHeight='25px'>How did we do?</Text>
              <Text color='brand.lightgrey'>Please let us know how we did with your support request. All feedback is appreciated to help us improve our offering!</Text>
              <Flex spacing='10px' color='brand.lightgrey' justifyContent='space-between'>
                <RatingBtn number={1} handle={()=>clickHandle(1)} back={latar[0]} col={warna[0]} />
                <RatingBtn number={2} handle={()=>clickHandle(2)} back={latar[1]} col={warna[1]} />
                <RatingBtn number={3} handle={()=>clickHandle(3)} back={latar[2]} col={warna[2]} />
                <RatingBtn number={4} handle={()=>clickHandle(4)} back={latar[3]} col={warna[3]} />
                <RatingBtn number={5} handle={()=>clickHandle(5)} back={latar[4]} col={warna[4]} />
                {/* <Btn />s */}
              </Flex>
              <Button w='100%' bg='brand.orange' color='brand.white' borderRadius='25px'
                      fontSize='15px' fontWeight='400' letterSpacing='2px' 
                      _hover={{bg:'brand.white', color:'brand.orange'}}
                      onClick={clickSubmit}
              >SUBMIT</Button>
            </Flex> :
             <Flex flexDir='column' justifyContent='space-between' alignItems='center'
             w={['90vw','62vh']} h={['90vw','62vh']} bg='brand.darkblue' 
             p={'40px 22px'} borderRadius='10px'
             spacing={['15px', '20px']} 
             >
              <Image src='/images/illustration-thank-you.svg' alt="thank you" w={['100px', '106px']} />
              <Text p={['5px 15px','7px 20px']} lineHeight={['13px', '15px']} borderRadius={25} fontSize={['13px', '15px']} bg='brand.mediumgrey' color="brand.orange">You selected {rating} out of 5</Text>
              <Text color="brand.white" fontSize="25px" fontWeight='bold'>Thank you!</Text>
              <Text fontSize={['13px', '15px']} color="brand.lightgrey" textAlign='center'>We appreciate you taking the time to give a rating. If you ever need more support, don’t hesitate to get in touch!</Text>
             </Flex>
          } 
        </Center>
      </main>
    </>
  )
}
